In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
data=pd.read_csv("5-udemy_courses.csv")
data.head()

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,1070968,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,True,200,2147,23,51,All Levels,1.5,2017-01-18T20:58:58Z,Business Finance
1,1113822,Complete GST Course & Certification - Grow You...,https://www.udemy.com/goods-and-services-tax/,True,75,2792,923,274,All Levels,39.0,2017-03-09T16:34:20Z,Business Finance
2,1006314,Financial Modeling for Business Analysts and C...,https://www.udemy.com/financial-modeling-for-b...,True,45,2174,74,51,Intermediate Level,2.5,2016-12-19T19:26:30Z,Business Finance
3,1210588,Beginner to Pro - Financial Analysis in Excel ...,https://www.udemy.com/complete-excel-finance-c...,True,95,2451,11,36,All Levels,3.0,2017-05-30T20:07:24Z,Business Finance
4,1011058,How To Maximize Your Profits Trading Options,https://www.udemy.com/how-to-maximize-your-pro...,True,200,1276,45,26,Intermediate Level,2.0,2016-12-13T14:57:18Z,Business Finance

In [4]:
data.dtypes

course_id                int64
course_title            object
url                     object
is_paid                   bool
price                    int64
num_subscribers          int64
num_reviews              int64
num_lectures             int64
level                   object
content_duration       float64
published_timestamp     object
subject                 object
dtype: object

In [8]:
#here as you can see that published_timestamp is in object datatype, but we need to convert into date time datatype as it contain
#information about published courses

In [5]:
#you can use shift+tab to find this parameter of any csv files
#1.  parse_dates:  parse_dates parameter for read_csv which allows you to define the names of the columns you want to be treated as dates or datetimes:
data1=pd.read_csv("5-udemy_courses.csv",parse_dates=['published_timestamp'])
data1.dtypes
data1.head()

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,1070968,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,True,200,2147,23,51,All Levels,1.5,2017-01-18 20:58:58+00:00,Business Finance
1,1113822,Complete GST Course & Certification - Grow You...,https://www.udemy.com/goods-and-services-tax/,True,75,2792,923,274,All Levels,39.0,2017-03-09 16:34:20+00:00,Business Finance
2,1006314,Financial Modeling for Business Analysts and C...,https://www.udemy.com/financial-modeling-for-b...,True,45,2174,74,51,Intermediate Level,2.5,2016-12-19 19:26:30+00:00,Business Finance
3,1210588,Beginner to Pro - Financial Analysis in Excel ...,https://www.udemy.com/complete-excel-finance-c...,True,95,2451,11,36,All Levels,3.0,2017-05-30 20:07:24+00:00,Business Finance
4,1011058,How To Maximize Your Profits Trading Options,https://www.udemy.com/how-to-maximize-your-pro...,True,200,1276,45,26,Intermediate Level,2.0,2016-12-13 14:57:18+00:00,Business Finance

# 1. Display Top 10 Rows of the DataSet

In [ ]:
data.head(10)

# 2. Check Last 5 rows of the Dataset

In [ ]:
data.tail(5)

# 3. Find Shape of our DataSet (number of rows & columns)

In [ ]:
data.shape

# 4. Get Information about our dataset like total number of rows, total number of columns, datatype of each column & memory requirement

In [ ]:
data.shape[0]
data.shape[1]
data.dtypes

# 5. Check Null Values in the Dataset

In [ ]:
data.isnull().values.any()
data.isnull().sum()
sns.heatmap(data.isnull())

# 6. Check for Duplicate Data & Drop them

In [ ]:
dup=data.duplicated().any()
print(dup)

In [ ]:
data=data.drop_duplicates()

In [ ]:
dup=data.duplicated().any()
print(dup)

# 7. Find out number of courses per subject  (also visualize it using seaborn library)

In [ ]:
data['subject'].value_counts()

In [ ]:
sns.countplot(x='subject',data=data)
plt.xlabel("Subjects", fontsize=13)
plt.ylabel("Number of Courses per Subject", fontsize=13)
plt.xticks(rotation=65)
plt.show()

# 8. For Which levels, Udemy are providing courses ? (also visualize it using seaborn library)

In [ ]:
data['level'].value_counts()

In [ ]:
sns.countplot(x ='level',data = data)
plt.xlabel("Levels", fontsize=13)
plt.ylabel("Number of Courses per level", fontsize=13)
plt.xticks(rotation=65)
plt.show()

# 9. Display the count of paid & free courses (with data visualization using seaborn)

In [ ]:
data["is_paid"].value_counts()

In [ ]:
sns.countplot(x ='is_paid',data = data)
mpl.xlabel("Levels", fontsize=13)
mpl.ylabel("Number of Free & Paid Courses", fontsize=13)
mpl.xticks(rotation=65)
mpl.show()

# 10. which courses has more lectures (Free or Paid) ?

In [ ]:
data.groupby('is_paid')['num_lectures'].mean().sort_values(ascending=False)

#paid

# 11. Which courses have higher number of subscribers Free or Paid ?

In [ ]:
data.groupby('is_paid')['num_subscribers'].sum().sort_values(ascending=False)

sns.barplot(x="is_paid",y="num_subscribers", data=data)

Index(['course_id', 'course_title', 'url', 'is_paid', 'price',
       'num_subscribers', 'num_reviews', 'num_lectures', 'level',
       'content_duration', 'published_timestamp', 'subject'],
      dtype='object')

In [ ]:
#free

# 12. Which level has the highest number of subscribers ?

In [ ]:
data.groupby('level')['num_subscribers'].sum().sort_values(ascending=False)
#all levels

In [ ]:
sns.barplot(x="level",y="num_subscribers", data=data)
plt.xticks(rotation=60)
plt.show()

# 13. Find Most Popular Course title

In [ ]:
data[data['num_subscribers'].max()==data['num_subscribers']] ['course_title']

# 14. Display 10 most popular courses  as per number of subscribers

In [ ]:
x=data.sort_values(by="num_subscribers", ascending=False)[
    ["course_title", "num_subscribers", "subject"]
].head(10)

In [ ]:
sns.barplot(x="num_subscribers",y="course_title",data=x)

# 15. Find the Courses which is having the highest number of reviews

In [ ]:
df.sort_values(by="num_reviews", ascending=False)[
    ["course_title", "num_reviews", "subject"]
].head(10)

In [ ]:
#mpl.figure(figsize=(10,4))
# sns.barplot(x="subject",y="num_reviews",data=data)

# 16. Does price affect number of reviews ?

In [ ]:
# course pricing does not dictate student engagement; expensive courses can generate just as much (or as little) review activity as cheaper or free courses.

In [ ]:
plt.figure(figsize=(15,3))
sns.scatterplot(x="price",y="num_reviews",data=data)

# 17. Find Total Number of courses realted to python

In [ ]:
python_df = data[data["course_title"].str.contains("Python", case=False)]

In [ ]:
len(python_df)

# 18. Display 10 Most Popular python courses as per number of subscribers

In [ ]:
python_df.groupby('course_title')['num_subscribers'].sum().sort_values(ascending=False).head(10)

#python=data[data['course_title'].str.contains('python',case=False)].sort_values(by="num_subscribers",ascending=False).head(10)

In [ ]:
sns.barplot(x="num_subscribers",y="course_title",data=python_df)